sensor:
  - platform: homeassistant
    entity_id: sensor.soc
    id: battery_soc
    on_value:
      then:
        lvgl.widget.update:
          id: battery_soc_button
          state:
            checked: !lambda return x;
      - lvgl.label.update:
          id: battery_soc_value
